version: '3'
services:
  master:
    image: mysql:latest
    container_name: master
    hostname: master
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
    ports:
      - "3308:3306"
    volumes:
      - ./data/master:/var/lib/mysql
    networks:
      - replicanet
    command: --server-id=1 --log-bin='mysql-bin-1.log'

  slave1:
    image: mysql:latest
    container_name: slave1
    hostname: slave1
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    ports:
      - "3309:3306"
    volumes:
      - ./data/slave1:/var/lib/mysql
    networks:
      - replicanet
    command: --server-id=2
    depends_on: 
      - master 

  slave2:
    image: mysql:latest
    container_name: slave2
    hostname: slave2
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    ports:
      - "3310:3306"
    volumes:
      - ./data/slave2:/var/lib/mysql
    networks:
      - replicanet
    command: --server-id=3
    depends_on: 
      - master 

networks:
  replicanet:
